package com.messi.languagehelper.dao;

import com.messi.languagehelper.db.LHContract;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 3): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = LHContract.DATABASE_VERSION;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        recordDao.createTable(db, ifNotExists);
        MeansDao.createTable(db, ifNotExists);
        PartsDao.createTable(db, ifNotExists);
        DictionaryDao.createTable(db, ifNotExists);
        TagDao.createTable(db, ifNotExists);
        EveryDaySentenceDao.createTable(db, ifNotExists);
        RoleDao.createTable(db, ifNotExists);
        DialogDaoDao.createTable(db, ifNotExists);
        SymbolListDaoDao.createTable(db, ifNotExists);
        WordListTypeDao.createTable(db, ifNotExists);
        WordDetailListItemDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        recordDao.dropTable(db, ifExists);
        MeansDao.dropTable(db, ifExists);
        PartsDao.dropTable(db, ifExists);
        DictionaryDao.dropTable(db, ifExists);
        TagDao.dropTable(db, ifExists);
        EveryDaySentenceDao.dropTable(db, ifExists);
        RoleDao.dropTable(db, ifExists);
        DialogDaoDao.dropTable(db, ifExists);
        SymbolListDaoDao.dropTable(db, ifExists);
        WordListTypeDao.dropTable(db, ifExists);
        WordDetailListItemDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(recordDao.class);
        registerDaoClass(MeansDao.class);
        registerDaoClass(PartsDao.class);
        registerDaoClass(DictionaryDao.class);
        registerDaoClass(TagDao.class);
        registerDaoClass(EveryDaySentenceDao.class);
        registerDaoClass(RoleDao.class);
        registerDaoClass(DialogDaoDao.class);
        registerDaoClass(SymbolListDaoDao.class);
        registerDaoClass(WordListTypeDao.class);
        registerDaoClass(WordDetailListItemDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
