package com.messi.languagehelper.dao;

import java.util.Map;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recordDaoConfig;
    private final DaoConfig meansDaoConfig;
    private final DaoConfig partsDaoConfig;
    private final DaoConfig dictionaryDaoConfig;
    private final DaoConfig tagDaoConfig;
    private final DaoConfig everyDaySentenceDaoConfig;
    private final DaoConfig roleDaoConfig;
    private final DaoConfig dialogDaoDaoConfig;
    private final DaoConfig symbolListDaoDaoConfig;
    private final DaoConfig wordListTypeDaoConfig;
    private final DaoConfig wordDetailListItemDaoConfig;


    private final recordDao recordDao;
    private final MeansDao meansDao;
    private final PartsDao partsDao;
    private final DictionaryDao dictionaryDao;
    private final TagDao tagDao;
    private final EveryDaySentenceDao everyDaySentenceDao;
    private final RoleDao roleDao;
    private final DialogDaoDao dialogDaoDao;
    private final SymbolListDaoDao symbolListDaoDao;
    private final WordListTypeDao wordListTypeDao;
    private final WordDetailListItemDao wordDetailListItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recordDaoConfig = daoConfigMap.get(recordDao.class).clone();
        recordDaoConfig.initIdentityScope(type);

        meansDaoConfig = daoConfigMap.get(MeansDao.class).clone();
        meansDaoConfig.initIdentityScope(type);

        partsDaoConfig = daoConfigMap.get(PartsDao.class).clone();
        partsDaoConfig.initIdentityScope(type);

        dictionaryDaoConfig = daoConfigMap.get(DictionaryDao.class).clone();
        dictionaryDaoConfig.initIdentityScope(type);

        tagDaoConfig = daoConfigMap.get(TagDao.class).clone();
        tagDaoConfig.initIdentityScope(type);

        everyDaySentenceDaoConfig = daoConfigMap.get(EveryDaySentenceDao.class).clone();
        everyDaySentenceDaoConfig.initIdentityScope(type);

        roleDaoConfig = daoConfigMap.get(RoleDao.class).clone();
        roleDaoConfig.initIdentityScope(type);

        dialogDaoDaoConfig = daoConfigMap.get(DialogDaoDao.class).clone();
        dialogDaoDaoConfig.initIdentityScope(type);
        
        symbolListDaoDaoConfig = daoConfigMap.get(SymbolListDaoDao.class).clone();
        symbolListDaoDaoConfig.initIdentityScope(type);
        
        wordListTypeDaoConfig = daoConfigMap.get(WordListTypeDao.class).clone();
        wordListTypeDaoConfig.initIdentityScope(type);

        wordDetailListItemDaoConfig = daoConfigMap.get(WordDetailListItemDao.class).clone();
        wordDetailListItemDaoConfig.initIdentityScope(type);

        recordDao = new recordDao(recordDaoConfig, this);
        meansDao = new MeansDao(meansDaoConfig, this);
        partsDao = new PartsDao(partsDaoConfig, this);
        dictionaryDao = new DictionaryDao(dictionaryDaoConfig, this);
        tagDao = new TagDao(tagDaoConfig, this);
        everyDaySentenceDao = new EveryDaySentenceDao(everyDaySentenceDaoConfig, this);
        roleDao = new RoleDao(roleDaoConfig, this);
        dialogDaoDao = new DialogDaoDao(dialogDaoDaoConfig, this);
        symbolListDaoDao = new SymbolListDaoDao(symbolListDaoDaoConfig, this);
        wordListTypeDao = new WordListTypeDao(wordListTypeDaoConfig, this);
        wordDetailListItemDao = new WordDetailListItemDao(wordDetailListItemDaoConfig, this);

        registerDao(record.class, recordDao);
        registerDao(Means.class, meansDao);
        registerDao(Parts.class, partsDao);
        registerDao(Dictionary.class, dictionaryDao);
        registerDao(Tag.class, tagDao);
        registerDao(EveryDaySentence.class, everyDaySentenceDao);
        registerDao(Role.class, roleDao);
        registerDao(DialogDao.class, dialogDaoDao);
        registerDao(SymbolListDao.class, symbolListDaoDao);
        registerDao(WordListType.class, wordListTypeDao);
        registerDao(WordDetailListItem.class, wordDetailListItemDao);
    }
    
    public void clear() {
        recordDaoConfig.getIdentityScope().clear();
        meansDaoConfig.getIdentityScope().clear();
        partsDaoConfig.getIdentityScope().clear();
        dictionaryDaoConfig.getIdentityScope().clear();
        tagDaoConfig.getIdentityScope().clear();
        everyDaySentenceDaoConfig.getIdentityScope().clear();
        roleDaoConfig.getIdentityScope().clear();
        dialogDaoDaoConfig.getIdentityScope().clear();
        symbolListDaoDaoConfig.getIdentityScope().clear();
        wordListTypeDaoConfig.getIdentityScope().clear();
        wordDetailListItemDaoConfig.getIdentityScope().clear();
    }

    public recordDao getRecordDao() {
        return recordDao;
    }

    public MeansDao getMeansDao() {
        return meansDao;
    }

    public PartsDao getPartsDao() {
        return partsDao;
    }

    public DictionaryDao getDictionaryDao() {
        return dictionaryDao;
    }

    public TagDao getTagDao() {
        return tagDao;
    }

    public EveryDaySentenceDao getEveryDaySentenceDao() {
        return everyDaySentenceDao;
    }

    public RoleDao getRoleDao() {
        return roleDao;
    }

    public DialogDaoDao getDialogDaoDao() {
        return dialogDaoDao;
    }
    
    public SymbolListDaoDao getSymbolListDaoDao() {
        return symbolListDaoDao;
    }
    
    public WordListTypeDao getWordListTypeDao() {
        return wordListTypeDao;
    }

    public WordDetailListItemDao getWordDetailListItemDao() {
        return wordDetailListItemDao;
    }

}
