package com.messi.languagehelper.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TAG.
 */
public class Tag {

    private Long id;
    private String name;
    private Long everyDaySentenceId;

    public Tag() {
    }

    public Tag(Long id) {
        this.id = id;
    }

    public Tag(Long id, String name, Long everyDaySentenceId) {
        this.id = id;
        this.name = name;
        this.everyDaySentenceId = everyDaySentenceId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getEveryDaySentenceId() {
        return everyDaySentenceId;
    }

    public void setEveryDaySentenceId(Long everyDaySentenceId) {
        this.everyDaySentenceId = everyDaySentenceId;
    }

}
