package com.messi.languagehelper.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Generated;

/**
 * Entity mapped to table TAG.
 */
@Entity
public class Tag {

    @Id(autoincrement = true)
    private Long id;
    private String name;
    private Long everyDaySentenceId;

    @Generated(hash = 2103553480)
    public Tag(Long id, String name, Long everyDaySentenceId) {
        this.id = id;
        this.name = name;
        this.everyDaySentenceId = everyDaySentenceId;
    }

    @Generated(hash = 1605720318)
    public Tag() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getEveryDaySentenceId() {
        return everyDaySentenceId;
    }

    public void setEveryDaySentenceId(Long everyDaySentenceId) {
        this.everyDaySentenceId = everyDaySentenceId;
    }

}
